config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index] do
    resources :questions, only: [:index], shallow: true do
      resources :answers, only: [:new, :create, :index, :show]
    end
  end
  resources :comments, only: [:index, :create]
  resources :users, except: [:delete, :new]


  get '/categories/:id/question', to: 'questions#show', as: :question

  get '/out_of_questions', to: 'static#out_of_questions'
  get '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root to: 'welcome#home'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :choice

  validates :user_id, uniqueness: { scope: :question_id, message: "can only answer a question once" }

  def calculate_count
    stats = {}
    stats[:all] = self.class.where("question_id = ?", self.question.id).size
    stats[:choice] = {}
    stats[:choice][:count] = self.class.where("question_id = ? AND choice_id = ?", self.question.id, self.choice.id).size
    stats[:choice][:instance] = self.choice
    stats
  end

  def calculate_percent(stats)
    choice = (stats[:choice][:count].to_f/stats[:all].to_f).round(2) * 100
    not_choice = (100 - choice)
    percent = {}
    percent[:choice] = choice.to_i.to_s + '%'
    percent[:not_choice] = not_choice.to_i.to_s + '%'
    percent
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :choices
  has_many :questions
  after_create :update_slug
  before_update :assign_slug
  validates :name, uniqueness: true, presence: true

  def generate_all_questions_for_category
    id_arr = self.choices.map {|choice| choice.id}
    id_combo_arr = id_arr.combination(2).to_a
    id_combo_arr.each do |id_combo|
      q = Question.new(category_id: self.id)
      if self.name.downcase.include?('nsfw')
        q.nsfw_flag = true
      end
      choice_a = Choice.find(id_combo[0])
      choice_b = Choice.find(id_combo[1])
      q.description = "#{choice_a.name} or #{choice_b.name}"
      q.choices << choice_a
      q.choices << choice_b
      q.save
    end
    puts "Generated #{id_combo_arr.size} questions from #{self.choices.size} choices for #{self.name}"
  end

  def create_slug
    name.downcase.gsub(" ", "-")
  end

  def update_slug
    update_attributes slug: assign_slug
  end

  def to_param
    slug
  end

  def self.find_by_slug(slug)
    Category.all.find {|c| c.slug == slug}
  end

  private

  def assign_slug
    self.slug = create_slug
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :questions
  has_many :answers

  validates :name, uniqueness: true, presence: true
  validate :content_or_img

  def content_or_img
    if !self.content && !self.img_url
      self.errors[:display] << "Must have content and/or image"
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :content, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  has_and_belongs_to_many :choices
  belongs_to :category
  has_many :answers
  has_many :users, through: :answers
  has_many :comments

  validate :valid_choices, :unique_choice_combo

  #validations
  def valid_choices
    if self.choices.size != 2
      self.errors[:choices] << "must have two choices"
    elsif self.choices.first == self.choices.last
      self.errors[:choices] << "must have two different choices"
    end
  end

  def unique_choice_combo
    all_choices = self.class.all.map do |question|
      question.choices
    end
    ca = self.choices.first
    cb = self.choices.last
    all_choices.each do |choice_combo|
      if choice_combo.include?(ca) && choice_combo.include?(cb)
        return self.errors[:choices] << "must have unique choice combinations"
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :answers
  has_many :questions, through: :answers

  validates :username, :email, uniqueness: true, presence: true
  # validates :zip_code, length: {is: 5}
  has_secure_password


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :is_authenticated?, only: [:show]
  before_action :nsfw_filter, only: [:show]

  def index
  end

  def show
    @answer = Answer.find_by(id: params[:id])
    @question = @answer.question
    @stats = @answer.calculate_percent(@answer.calculate_count)
    @comments = @question.comments
  end

  def new
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to @answer
    else
      flash[:reanswer_message] = "You've already answered this question! Try a new one:"
      redirect_to question_path(rand_slug)
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :user_id, :choice_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index

  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      answer = @comment.user.answers.last
      question = @comment.question
      redirect_to answer
    else
      flash[:comment_message] = "Cannot submit empty comment."
      redirect_to controller: 'answers', action: 'show', id: @comment.user.answers.last.id, question_id: @comment.question.id
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:question_id, :user_id, :content)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :is_authenticated?, only: [:show]
  before_action :nsfw_filter, only: [:show]

  def index
  end

  def show
    @question = select_unanswered_question_by_category(params[:id])
    @comments = @question.comments
  end

  private

  def question_params
    params.require(:question).permit(:description, :category_name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to '/'
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def out_of_questions

  end

  def about

  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @answers = current_user.answers
    @comments = current_user.comments
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if current_user.update(user_params)
      redirect_to current_user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email, :zip_code, :dob)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/answers/show.html.erb
<h3>Category: <%= @question.category.name %></h3>

<div class="jumbotron">
  <h1>Would you rather...</h1>
</div>

<div class="row">
  <div class="col-lg-1 col-md-1 col-sm-1"></div>
  <% @question.choices.each do |choice| %>
    <div class="col-lg-5 col-md-5 col-sm-5 text-center" >
    <% if choice.img_url %>
      <%= image_tag choice.img_url, class: "answer-img-thumbnail" %>
      <h4><%= choice.name%></h4>

      <% if choice == @answer.choice %>
        <h4><%= @stats[:choice] %></h4>
      <% else %>
        <h4><%= @stats[:not_choice] %></h4>
      <% end %>

    <% else %>
      <div class="answer-box"><p><%= choice.content %></p></div>
      <% if choice == @answer.choice %>
        <h4><%= @stats[:choice] %></h4>
      <% else %>
        <h4><%= @stats[:not_choice] %></h4>
      <% end %>

    <% end %>
    </div>
  <% end %>
  <div class="col-lg-1 col-md-1 col-sm-1"></div>
</div>

<br>
<div class="row text-center">
  <% if remaining_questions.empty? %>
    <%= button_to "Give Me More!", out_of_questions_path, method: "get", class: "btn-lg" %>
  <% else %>
    <%= button_to "Give Me More!", {controller: "questions", action: "show", id: rand_slug }, method: "get", class: "btn-lg more-btn" %>
  <% end %>
</div>

<hr class="large">
<div class="row">
  <h3>Comments</h3>
  <% if flash[:comment_message] %>
    <p class="warning"><%= flash[:comment_message] %></p>
  <% end %>

  <div class="col-lg-12 col-md-12 col-sm-12 comment-box" >
      <div class="form-group">
        <%= form_tag comments_path method: :post do %>
          <%= hidden_field_tag :'comment[user_id]', current_user.id %>
          <%= hidden_field_tag :'comment[question_id]', @question.id %>
          <%= text_area_tag :'comment[content]', nil, placeholder: "Enter your comment here...", class:"form-control" %>
          <%= submit_tag "Submit", method: :post, class: "btn btn-danger btn-sm" %>
        <% end %>
      </div>

  <hr class="small">

  <% if @comments.empty? %>
    <p>No comments yet!</p>
  <% else %>
    <ul><% @comments.each do |comment| %>
      <li><strong><%= comment.user.username %></strong> - <%= comment.content %></li>
    <% end %></ul>
  <% end %>
</div>
</div>

app/views/questions/show.html.erb
<% if flash[:reanswer_message] %>
  <p class: "warning"><%= flash[:reanswer_message] %></p>
<% end %>
<br>

<h3>Category: <%= @question.category.name %></h3>

<div class="jumbotron">
  <h1>Would you rather...</h1>
</div>

<div class="row">
  <div class="col-lg-1 col-md-1 col-sm-1"></div>
  <% @question.choices.each do |choice| %>
    <div class="col-lg-5 col-md-5 col-sm-5 text-center" >
    <%= form_tag question_answers_path(@question) do %>
      <%= hidden_field_tag :'answer[choice_id]', choice.id%>
      <%= hidden_field_tag :'answer[user_id]', current_user.id%>
      <%= hidden_field_tag :'answer[question_id]', @question.id%>
      <% if choice.img_url %>
          <%= image_submit_tag choice.img_url, class: "img-thumbnail" %>
          <h4><%= choice.name%></h4>
      <% else %>
          <%= submit_tag choice.content, class: "choice-btn"%>
      <% end %>
    <% end %>
    </div>
  <% end %>
  <div class="col-lg-1 col-md-1 col-sm-1"></div>
</div>


<hr class="large">
<div class="row">
  <h3>Comments</h3>

  <div class="col-lg-12 col-md-12 col-sm-12 comment-box" >
  <% if @comments.empty? %>
    <p>No comments yet!</p>
  <% else %>
    <ul>
    <% @comments.each do |comment| %>
      <li><strong><%= comment.user.username %></strong> - <%= comment.content %></li>
      <hr>
    <% end %>
    </ul>
  <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="jumbotron">
  <h1>Edit Profile</h1>
</div>

<br>
<h3>Username: <%= current_user.username %></h3>
<br>
<br>


<%= form_for current_user do |f| %>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label 'Email' %>
      <%= f.text_field :email, class: "form-control" %>
      <%= f.label 'New Password' %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label 'Confirm Password' %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

  <div class="form-group col-md-12">
    <%= f.submit "Submit", class:"btn btn-danger" %>
  </div>
<% end %>

app/views/users/new.html.erb
<div class="form-group col-md-12">
  <h1>Sign Up</h1>
</div>

<%= form_for @user do |f| %>
  <div class="form-row">
    <div class="form-group col-md-4">
      <%= f.label 'Username' %>
      <%= f.text_field :username, class: "form-control" %>
      <%= f.label 'Password' %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label 'Confirm Pasword' %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.label 'Email' %>
      <%= f.text_field :email, class: "form-control" %>
      <%= f.label 'Birthday' %>
      <%= f.date_field :dob, class: "form-control" %>
    </div>
  <div class="form-group col-md-12">
    <%= f.submit "Submit", class:"btn btn-danger" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="jumbotron">
  <h1>Hello, <%= current_user.username %></h1>
</div>


<h3>Email: <%= current_user.email %></h3>
<h3>Birthday: <%= current_user.dob.strftime('%D') %></h3><br>
<div class="col-lg-12 col-md-12 col-sm-12">
  <%= button_to "Edit Profile", edit_user_path, method: :get, class: "btn btn-danger btn-sm"%><br>
</div>

<div class="col-lg-6 col-md-6 col-sm-6">
  <h4>You've answered <%= pluralize(@answers.size,'questions') %>.</h4>
  <div id="user_answers_box" class="panel panel-default">
    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#user_answers">Show Answers</button>
    <div id="user_answers" class="collapse panel-body">
      <ul>
        <% @answers.each do |answer| %>
          <li>Between <strong><%= answer.question.description %></strong>, you picked <strong class="picked"><%= answer.choice.name %></strong>.</li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="col-lg-6 col-md-6 col-sm-6">
  <h4>You've made <%= pluralize(@comments.size,'comment') %>.</h4>
  <div id="user_comments_box" class="panel panel-default">
    <button type="button" class="btn btn-info" data-toggle="collapse" data-target="#user_comments">Show Comments</button>
    <div id="user_comments" class="collapse panel-body">
      <% if @comments.empty? %>
        <p>No comments yet!</p>
      <% else %>
        <ul>
        <% @comments.each do |comment| %>
          <li> <strong><%= link_to comment.question.description, find_user_answer(comment.question) %>:</strong class="picked"> <br> <%= comment.content %></li>
        <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>