config/routes.rb
Rails.application.routes.draw do
  resources :categories, only: [:index] do
    resources :questions, only: [:index], shallow: true do
      resources :answers, only: [:new, :create, :index, :show]
    end
  end
  resources :comments, only: [:index, :create]
  resources :users, except: [:delete, :new]


  get '/categories/:id/question', to: 'questions#show', as: :question

  get '/out_of_questions', to: 'static#out_of_questions'
  get '/about', to: 'static#about'
  get '/contact', to: 'static#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  root to: 'welcome#home'

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :choice

  validates :user_id, uniqueness: { scope: :question_id, message: "can only answer a question once" }

  def calculate_count
    stats = {}
    stats[:all] = self.class.where("question_id = ?", self.question.id).size
    stats[:choice] = {}
    stats[:choice][:count] = self.class.where("question_id = ? AND choice_id = ?", self.question.id, self.choice.id).size
    stats[:choice][:instance] = self.choice
    stats
  end

  def calculate_percent(stats)
    choice = (stats[:choice][:count].to_f/stats[:all].to_f).round(2) * 100
    not_choice = (100 - choice)
    percent = {}
    percent[:choice] = choice.to_i.to_s + '%'
    percent[:not_choice] = not_choice.to_i.to_s + '%'
    percent
  end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :choices
  has_many :questions
  after_create :update_slug
  before_update :assign_slug
  validates :name, uniqueness: true, presence: true

  def generate_all_questions_for_category
    id_arr = self.choices.map {|choice| choice.id}
    id_combo_arr = id_arr.combination(2).to_a
    id_combo_arr.each do |id_combo|
      q = Question.new(category_id: self.id)
      if self.name.downcase.include?('nsfw')
        q.nsfw_flag = true
      end
      choice_a = Choice.find(id_combo[0])
      choice_b = Choice.find(id_combo[1])
      q.description = "#{choice_a.name} or #{choice_b.name}"
      q.choices << choice_a
      q.choices << choice_b
      q.save
    end
    puts "Generated #{id_combo_arr.size} questions from #{self.choices.size} choices for #{self.name}"
  end

  def create_slug
    name.downcase.gsub(" ", "-")
  end

  def update_slug
    update_attributes slug: assign_slug
  end

  def to_param
    slug
  end

  def self.find_by_slug(slug)
    Category.all.find {|c| c.slug == slug}
  end

  private

  def assign_slug
    self.slug = create_slug
  end
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :category
  has_and_belongs_to_many :questions
  has_many :answers

  validates :name, uniqueness: true, presence: true
  validate :content_or_img

  def content_or_img
    if !self.content && !self.img_url
      self.errors[:display] << "Must have content and/or image"
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question
  validates :content, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  has_and_belongs_to_many :choices
  belongs_to :category
  has_many :answers
  has_many :users, through: :answers
  has_many :comments

  validate :valid_choices, :unique_choice_combo

  #validations
  def valid_choices
    if self.choices.size != 2
      self.errors[:choices] << "must have two choices"
    elsif self.choices.first == self.choices.last
      self.errors[:choices] << "must have two different choices"
    end
  end

  def unique_choice_combo
    all_choices = self.class.all.map do |question|
      question.choices
    end
    ca = self.choices.first
    cb = self.choices.last
    all_choices.each do |choice_combo|
      if choice_combo.include?(ca) && choice_combo.include?(cb)
        return self.errors[:choices] << "must have unique choice combinations"
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :answers
  has_many :questions, through: :answers

  validates :username, :email, uniqueness: true, presence: true
  # validates :zip_code, length: {is: 5}
  has_secure_password


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :is_authenticated?, only: [:show]
  before_action :nsfw_filter, only: [:show]

  def index
  end

  def show
    @answer = Answer.find_by(id: params[:id])
    @question = @answer.question
    @stats = @answer.calculate_percent(@answer.calculate_count)
    @comments = @question.comments
  end

  def new
  end

  def create
    @answer = Answer.new(answer_params)
    if @answer.save
      redirect_to @answer
    else
      flash[:reanswer_message] = "You've already answered this question! Try a new one:"
      redirect_to question_path(rand_slug)
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:question_id, :user_id, :choice_id)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def out_of_questions

  end

  def about

  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @answers = current_user.answers
    @comments = current_user.comments
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if current_user.update(user_params)
      redirect_to current_user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :password, :email, :zip_code, :dob)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Would You Rather</title>
    <link href="https://fonts.googleapis.com/css?family=Noticia+Text:400,400i,700,700i|Open+Sans:400,400i,600,600i,700,700i|Rock+Salt" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag "custom_styles" %>
  </head>
  <body>
    <nav class="navbar">
    <div class="container">
      <div class="navbar_header">
        <button type="button" id="hamburger" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-elem" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a href="<%= root_url %>" class="navbar-brand"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a>
      </div>
      <div class="collapse navbar-collapse" id="collapse-elem">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
          <% if current_user %>
            <li><%= link_to "Profile", user_path(current_user) %></li>
            <% if remaining_questions.empty? %>
              <li><%= link_to "Play", out_of_questions_path %></li>
            <% else %>
              <li><%= link_to "Play", controller: "questions", action: "show", id: rand_slug %></li>
            <% end %>
          <li class="dropdown">
            <a href="<%= categories_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% clean_categories.each do |c| %>
                <li><%= link_to c.name, {controller: "questions", action: "show", id: c.slug }%></li>
              <% end %>
              <li role="separator" class="divider"></li>
              <% nsfw_categories.each do |c| %>
                <li><%= link_to c.name, {controller: "questions", action: "show", id: c.slug } %></li>
              <% end %>
            </ul>
          </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <%= button_to "Log Out", logout_path, method: :delete, id: "logout", class: "btn btn-danger btn-sm"%>
          <% else %>
            <li><%= link_to "Log In", login_path %></li>
            <li><%= link_to "Sign Up", signup_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
    </nav>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>

  <script src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </body>
</html>